config/routes.rb
Rails.application.routes.draw do
  
  root"pages#home"

  get "about" => "pages#about"
  get "schedule" => "pages#schedule"
  get "ecourse" => "pages#ecourse"
  get "vision" => "pages#vision"
  get "founder" => "pages#founder"
  get "board" => "pages#board"
  get "inspiration" => "pages#inspiration"
  get "science" => "pages#science"
  get "students" => "pages#students"
  get "gallery" => "pages#gallery"
  get "donations" => "pages#donations"
  get "faqs" => "pages#faqs"
  get "speaker" => "pages#speaker"
  get "exhibitions" => "pages#exhibitions"
  get "fundraise" => "pages#fundraise"
  get "volunteer" => "pages#volunteer"
  get "press" => "pages#press"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about 
end 

 def schedule
  end

   def ecourse
  end

   def vision
  end

   def founder
  end

   def board
  end

   def inspiration
  end

   def science
  end

   def students
  end

   def gallery
  end

   def donations
  end


   def faqs
  end

   def speaker
  end

   def press
  end

   def exhibitions
  end

   def fundraise
  end

   def teacher
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
<div class="container">
<div class="row">


<div class="col-md-4 md-margin-bottom-40">
<div class="headline"><h2>Get Involved</h2></div>
<p><%= link_to "Exhibitions", exhibitions_path %><br>
<p><%= link_to "Activites", fundraise_path %><br>
<div class="headline"><h2>Stay Connected</h2></div>
<ul class="social-icons">
<li><a href="#" data-original-title="Facebook" class="social_facebook"></a></li>
<li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li>
<li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>

</ul>
</div>


<div class="col-md-4">
<div class="headline"><h2>Learn More</h2></div>
<p><%= link_to "FAQs", faqs_path %></p>
<p><a href="http://healingicons.blogspot.com/" class="">Visit our Blog</a></p>



<div class="headline"><h2>Contact Us</h2></div>
<address class="md-margin-bottom-40">
Healing Icons <br />
P.O. Box 5194, Columbia, SC 29205<br />
Phone: (803) 429-4151 <br />
Email: <a href="mailto:info@healingicons.org" class="">info@healingicons.org</a>
</address>
</div>
</div>
</div>




<div class="copyright">
<div class="container">
<div class="row">
	
<p class="copyright-space">
2014 &copy; Healing Icons 
</p>

</div>
</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>"><i class="fa fa-codepen"></i> Healing Icons</a>
  </div>


  <div class="collapse navbar-collapse navbar-ex1-collapse">
     <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
         <li><%= link_to "Schedule", schedule_path %></li>
          <li class="divider"></li>
         <li><%= link_to "eCourse", ecourse_path %></li>
          </ul>
        </li>


<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Impact <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Vision", about_path %></li>
          <li class="divider"></li>
         <li><%= link_to "Philosophy", vision_path %></li>
          </ul>
        </li>

<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">People <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Founder", founder_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Board", board_path %></li>
          </ul>
        </li>



<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
                 <li><%= link_to "Students", students_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Gallery", gallery_path %></li>
          </ul>
        </li>

        <li><%= link_to "Inspiration", inspiration_path %></li>

      <li><%= link_to "Help Us", donations_path %></li>
    </ul>
</li>

     

     
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- References: https://github.com/fancyapps/fancyBox -->
<!-- References: https://github.com/fancyapps/fancyBox -->

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
    <link rel="stylesheet" href="/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
    <script type="text/javascript" src="/fancybox/jquery.fancybox.pack.js"></script>

</head>
<body>


<%= render 'layouts/header' %>
 <div class="container-fluid">
	<%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
	
   <section id="news" class="white-bg padding-top-bottom">
		
<div class="container">
				
				<h1 class="section-title">Healing Icons<small>®</small></h1>
				<center><h2>Solid Mission with a Global Vision</h2></center>
				<p class="section-description">We’re a non-profit on a mission to teach art-making as a form of healing to every cancer survivor on the planet.<br>
 Through our community events, art exhibitions, and creative workshops for cancer survivors, their families and caregivers, <br>we provide relief, reduce suffering and make positive change in people’s lives.</p>

<br>
<br>
<center><div class="responsive-video">
<iframe src= "http://player.vimeo.com/video/9679622" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div></center> 


<br>
<br>
<br>
<br>

				<div class="timeline">
					<div class="date-title">
						<span>Cancer Diagnosis</span>
					</div>
				
<div class="row">
					
						<div class="col-sm-6 news-item scrollimation fade-up">

							<div class="news-content">
								<div class="date">
									<p>1.4</p>
									<small>Million</small>
								</div>
							
								<h2 class="news-title">People Get Cancer Every Year</h2>
							
								<p>It is hard to imagine what 1.4 million people look like but one in every four might be easier. One in every four people in our world will face the Cancer Journey, a grueling physical, emotional, and spiritual journey. If you’re a cancer survivor, you get this.  If you are not, let us introduce you to a few of these millions of courageous survivors. Let them show you how art helped save their lives.</p>
								
							</div>
						</div>


						
						<div class="col-sm-6 news-item right scrollimation fade-up">
							
								
							
								 <center><img class="img-responsive img-center" src="assets/board-meeting.jpg" alt=""/></center>
								
						</div>
								

						
</div>
					
<div class="row">
					
						<div class="col-sm-6 news-item scrollimation fade-up">
						
							
                      <center><img class="img-responsive img-center" src="assets/circle.jpg" alt="Circle Mandala"/></center>


						</div>
						
						<div class="col-sm-6 news-item right scrollimation fade-up">
						
							<div class="news-content">
	                                <div class="date">
									<p><i class="fa fa-signal"></i></p>
									<small>Stress</small>
								
								    </div>
							
								<h2 class="news-title">Stess=Weakened Immune Systems</h2>
							
								<p>We invite you to put yourselves in their shoes. Follow them through their doctor’s appointments, their chemo and radiation treatments, their pain and nausea, fatigue and sleeplessness, their body scars and loss of hair, their fight for life! No one chooses this path but everyone needs a helping hand through it.</p>
								
							</div>
						
					</div>
</div>

<div class="row">

									
						<div class="col-sm-6 news-item right scrollimation fade-up">
						
							
                      <center><img class="img-responsive img-center" src="assets/support.jpg" alt=""/></center>


						</div>
						<div class="col-sm-6 news-item scrollimation fade-up">
		
						
							<div class="news-content">
	                                <div class="date">
									<p><i class="fa fa-stethoscope"></i></p>
									<small>Help</small>
								
								    </div>
							
								<h2 class="news-title">Finding the Right Kind of Support</h2>
							
								<p>Overwhelmed by what is happening to our bodies, it can be extremely difficult to even identify what is being felt on the inside. A participant once said, “I feel as though I have un-namable overwhelming sensations that whirl around inside my head and my body but they are not speech ready.”  How do we experience what is happening in our lives when we can’t put words to it…when <a href="#" class=""><span class="color-white">Sometimes Words Are Not Enough.</span></a> This is where Healing Icons® comes into play.</p>
								
							</div>
						
					</div>

						
</div>


					<div class="date-title">
						<span>Art as Healing</span>
					</div>
					
<div class="row">	
					
						<div class="col-sm-6 news-item scrollimation fade-up">
						
							<div class="news-content">
							
								
								
								<h2 class="news-title">Healing Icon<small>®</small></h2>
								
								
								<p>What is a Healing Icon<small>®</small>? The word icon comes from the Greek word eikon, meaning likeness. So a Healing Icon is simply a visually representation of the cancer survivor’s journey, each one being uniquely personal and intimate.</p>
								
								
							</div>
						</div>
						
						<div class="col-sm-6 news-item scrollimation fade-up">
						
					 <center><img class="img-responsive img-center" src="assets/tree-icon.jpg" alt=""/></center>


						</div>
						
</div>
					
				
<div class="row">	
					
						
						<div class="col-sm-6 news-item right scrollimation fade-up">
							<div class="news-content">
							
								
								
								<h2 class="news-title">Creative Freedom</h2>
								
								
								<p> This is art making that comes from the gut, honest and raw. It is not about talent and right or wrong. We experience an awesome sense of freedom while having loads of fun getting messy, getting lost and getting very curious. As you begin to get lost in the process of art making, slowly your creations will begin to speak to you, giving voice to what was once unspeakable.</p>
								
								
							</div>
						</div>

						<div class="col-sm-6 news-item scrollimation fade-up">
						
						
					 <center><img class="img-responsive img-center" src="assets/student-working.jpg" alt=""/></center>


						</div>
						
						
</div>
					
		
<div class="row">	
					<div class="col-sm-6 news-item scrollimation fade-up">
						
							<div class="news-content">
							
								
								
								<h2 class="news-title">Post Treatment</h2>
								
								
								<p> After treatment many survivors feel strangely alone and abandoned especially if a cancer survivorship plan has not been put into place. As the journey forward begins, there are many quality of life issues to face. Post-treatment challenges such as the short and long term side effects of treatment, stress of years of follow up appointments, fear of reoccurrence… In other words, transitioning from active treatment into recovery isn’t easy.  Healing Icons classes offers support during active treatment and beyond.</p>
								
								
							  </div>
					</div>

						
						
						<div class="col-sm-6 news-item right scrollimation fade-up">
						
					 <center><img class="img-responsive img-center" src="assets/testimonial.jpg" alt=""/></center>


						</div>
						
						
					</div>
						<div class="date-title">
						<span>Research Shows</span>
					</div>
					</div>

					<p class="section-description">Research from the Jefferson-Myrna Brind Center of Integrative Medicine shows that mindfulness meditation coupled with art therapy can successfully decrease stress symptoms- Yay! We knew this already but nice when studies point to what we know and love!  Our mindful art-making practices produce the same benefits as meditation, improving your ability to handle and recover from stress while lowering stress hormone levels.</p>
				
			

					</section>
</div>
				

		

app/views/pages/donations.html.erb
<div class="container">
<div class="title-box">
<div class="title-box-text">Healing Icons is a<span class="color-green"> 501(c)3 non-profit</span> for adult cancer survivors.</div>
<p>Please help us foster hope and healing to women with cancer as well has to those who have suffered tremendous loss.<br> We welcome support throughout the year.<br /> <br>Honor a special occassion, a loved one or a member of your health care team with a donation to Healing Icons.</p>
</div>
</div>
<div class="margin-bottom-30"></div>
<div class="container">	
<!-- Service Blcoks -->
<div class="row servive-block margin-bottom-10">
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-grey">
<h4>$100</h4>
<div><i class="fa fa-heart-o"></i></div>
<p>$100 provides art supplies for our Oncology Workshops</p>
</div>
</div>
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-grey">
<h4>$200</h4>
<div><i class="fa fa-heart-o"></i></div>
<p>$200 sponsors a student for one Oncolgy Workshop</p>
</div>
</div>
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-grey">
<h4>$250</h4>
<div><i class="fa fa-heart-o"></i></div>
<p>$250 funds reproduction of new work for traveling exhibition</p>
</div>
</div>
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-grey">
<h4>$500</h4>
<div><i class="fa fa-heart-o"></i></div>
<p>$500 maintains the Student Scholarship Program</p>
</div>
</div>
</div>
<div class="row servive-block margin-bottom-10">
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-sea">
<h4>$1000</h4>
<div><i class="fa fa-heart"></i></div><br />
<p>$1,000 sustains our Travel Retreats</p>
</div>
</div>
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-sea">
<h4>$1500</h4>
<div><i class="fa fa-heart"></i></div><br />
<p>$1,500 assists Annual Exhibition "Insights into Healing" </p>
</div>
</div>
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-sea">
<h4>$2,500</h4>
<div><i class="fa fa-heart"></i></div><br />
<p>$2,500 assures our Women's Oncology Programming thrives</p>
</div>
</div>
<div class="col-md-3 col-sm-6">
<div class="servive-block-in servive-block-colored servive-block-sea">
<h4>$5,000</h4>
<div><i class="fa fa-heart"></i></div><br />
<p>$5,000 preserves "Sometimes Words Are Not Enough" </p>
</div>
</div>
<br />
</div>
<div class= "container">
<div class="row">
<div class= "col-md-4">
<div id='razoo_donation_widget'><span><a href="http://www.razoo.com/story/Healing-Icons">Donate to HEALING ICONS</a> at <a href="http://www.razoo.com/">Razoo</a></span></div><script type='text/javascript'>var r_params = {"title":"HEALING ICONS","short_description":"","long_description":" ","color":"#6ec9c9","errors":false,"donation_options":{"100":"Aids in Providing Excellent Art Supplies for our women's oncology workshops","195":"Pays a Workshop Fee","200":"Sponsors a Student for one of our Women's Oncolgy Workshops"},"image":"true"};var r_protocol=(("https:"==document.location.protocol)?"https://":"http://");var r_path='www.razoo.com/javascripts/widget_loader.js';var r_identifier='Healing-Icons';document.write(unescape("%3Cscript id='razoo_widget_loader_script' src='"+r_protocol+r_path+"' type='text/javascript'%3E%3C/script%3E"));</script>
</div>
<div class= "col-md-8">
<div class="margin-bottom-3"></div>
<p><h3><i class="fa fa-arrow-up fa-lg"></i> Help Our Mission Grow:</h3><br />
Cancer stops you in your tracks. Heartbreaking losses and regrets deaden your spirit. They turn your life upside down, inside out. Alone we can’t, but in small gatherings we can together we can begin to understand and heal. One story, one creation at a time.
<br />
<br />
<h4>A student reflection from Insights into Healing:</h4>
"Cancer creates many dualities. Chemotherapy saves your life, but strips you of your identity<br />
Renders you anonymous-bald head, bland face, no eyebrows, no eyelashes. Dealing with my disease leads to another duality.<br />
My outward persona and my inward self. <br />
On the outside, I am strong and proud, a fierce warrior.<br />
Inside, the fighter seeks a soft blue sanctuary, a quiet place for rest.<br />
Cancer caused intertwined feelings, love and fear.<br />
I am not who I was….I am better."<br />
<strong>-Dualities words inspired from creating a 3D Mask of Change. By R.B. 1999</strong>
<br />
<br />
</p>
</div>
</div>
</div>
</div>

app/views/pages/ecourse.html.erb
<div class="container">
<div class="row">
        <div class="col-md-12 coming-soon">
<center><h1>Healing Icons<small>®</small> at your own pace.</h1></center>
<br>


 <center><h1 class="section-title">Coming Soon!</h1></center>
   <p class="section-description">Our eCourse is a visual tool built around simple design and the creative process.  Anyone can do it.
<br>You just worry about creating awesome stuff.  We'll handle the rest.<br>Sign up now to join the waiting list for our first eCourse!</p>
<br>
<br>
</div>
</div>
</div>



<div class="container">
<div class="row margin-bottom-50">
<div class="col-md-4 service-alternative">
<div class="service">
<div class="desc">
<h4><i class="fa fa-cogs fa-lg"></i> Courageous Creating</h4>
<p>A six week ecourse exploring the art<br> of mandala making:
<br><br>Decrease stress and anxiety.
<br>Discover a supportive nurturing community. 
<br>Learn there is no right or wrong way to create.
<br>Cultivate time for art, play = fun = rest.
<br>Quiet the thunderous roar of  mind stuff.
<br><br>The goal of creating a mandala is not an intellectual path but a journey that trusts and supports a willingness to open into the playful intuitive mystery of the creative process.  Here is where your gut instinct, your intuition comes out to play.
</p>
</div>
</div>
</div>
<div class="col-md-4 service-alternative">
<div class="service">
<div class="desc">
<h4><i class="fa fa-map-marker fa-lg"></i> About the Class</h4>
<p>Creating mandalas is an ancient practice we have revamped for new times, our time.<br><br> Mandala, the Sanskrit word for circle, is an archetypal symbol of balance, wholeness and unity.   They have been created for centuries as meditational symbols that when contemplated, lead to self-awareness, insight and peace.<br><br>Think: stained-glass, rose windows in cathedrals, moon gazing, Sufi dancers, and Buddhist sand painting.</p>
</div>
</div>
</div>
<div class="col-md-4 service-alternative">
<div class="service">
<i class="icon-plane service-icon"></i>
<div class="desc">
<h4><i class="fa fa-heart fa-lg"></i> Your Guide</h4>
<p>To freely create mandalas cultivates a skillful practice that calms and anchors us into a quiet stillness that can be found within the cancer survivor’s life.<br><br>Study with Heidi Darr-Hope, a seasoned professional artist with over 40 years of art-making experience and 20 years of creating with cancer patients.<br><br>Our approach is unique and our methods are 100% evidence-based. You are in good hands.</p>

</div>
</div>
</div>
</div>
</div>

app/views/pages/exhibitions.html.erb
<div class="container">


Sometimes Words Are Not Enough

Uplifting.  Inspiring.  Honest.

Comments from our Exhibition Guests: 
 “This is a profound way for healthy people to gain a better understanding of what cancer patients are going through.  I can see and feel these survivors’ wide range of thoughts and emotions, from tremendous joy to painful remorse.  Thank you for this exhibition!”

“It is obvious that each survivor used the creative process to look deep within themselves to find fear, pain, anger...  Then victoriously worked through it all to embrace the courage & tenacity was there all along.  Amazing!”

“The icons in this exhibition are so heartwarmingly beautiful.  They gave me a sense of peace as we bury a dear friend tomorrow, who died from cancer after a long struggle.”

“How courageous and thought provoking!  Artistically Well Done.  Beautiful and Uplifting!”

This is an exhibition created by ordinary people from all walks of life and they do not consider themselves artists.  The single thread that runs through this exhibition is that they all have heard the three words that change a life forever, “You Have Cancer.” 
You might ask why anyone would want to create from the place of pain and struggle that comes with cancer, much less view an exhibition about it.  We believe several things:
The joys in life are lived; the pain is life is expressed.   Once pain is released, we are enlivened and move towards living more fully.
Pain is universal - no matter the issue - so this exhibition speaks to a wide audience.
Difficult issues are hard to talk about.  We need a threshold, an entryway that helps us find our way into these conversations.  These works of art do that.
“The aim of art is to represent not the outward appearance of things, but their inward significance.”  - Aristotle    Art helps us understand what it is to be human.
As one viewer said, “This exhibition is not just about cancer, it is about the incredible resiliency of the human spirit.  Inspiring and Uplifting!”  
We all have been touched by cancer in some way, whether a diagnosis has been received personally, or we have journeyed through it with a family member, friend, co-worker or neighbor.  

The works in this exhibition show how participants in Healing Icons®
Decrease stress while increasing their coping skills
Discover a supportive nurturing community 
Learn the silent, powerful language of art
Create a series of Healing Icons® that symbolically represent the current issues in their lives
Uncover a deep wellspring of emotional and spiritual healing

	Each unique piece of artwork:

Tells a story

Offers inspiration and insight into the world of cancer

Spreads the gift of hope and healing

VISIT STUDENT GALLERY
Sometimes Words Are Not Enough 
Highlights of places we have traveled: 
Palliative Medicine Conference, Sponsored by the Mayo Clinic, Orlando, FL
	Common Boundary Conference, Washington, DC
	South Eastern Very Special Arts Conference, Atlanta, GA
	23rd Annual Congress of the Oncology Nursing Society, San Francisco, CA
Georgia College and State University, Milledgeville, GA
	The University of Charleston, Charleston, WV
The Art of Survival, The Music of Life, Amgen Inc. San Diego, CA San Francisco, CA San Antonio, TX
	Dock Street Theater, Guerilla Theatre’s production of Wit, Charleston, SC

Book Your Exhibition Today

Where there is a wall there is a way!

Please don’t think you have to have a gallery space within a state-of-the-art institution to book our exhibition.   Our works have been displayed in church parlors, doctors’ waiting rooms, office break rooms, bank and theatre lobbies.  Our staff will assist you in finding just the right space within your facility.

Exhibitor Responsibilities
The exhibitor is responsible for booking reservations, publicity, unpacking and repacking of show, handling and hanging of shows, picking up and returning the exhibits (if within driving distance – otherwise shipping arrangements will be made) and assumes liability for rented exhibitions. 

Payment
If the exhibition is available, exhibitors will receive a confirmation letter and rental-fee invoice.  Payment should be sent no fewer than 30 days before the scheduled pick-up/ delivery time of the exhibition.  Invoices must be paid in full before any exhibition is released.

Information
TEP Coordinator
803-429-4151
Info@healingicons.org




Exhibitions
This features 2-D and 3-D full-color fine art reproductions of mixed media artwork created by adult cancer patients.  Every exhibition contains two original works of art to enhance the viewer’s experience.

All works are mounted on foam core, sealed with a protective coating and framed without glass in a light weight brush metal molding, wired for hanging
Each exhibition includes an introduction panel and two process panels showing students working. 
Each exhibition is accompanied by an informational DVD, which may remain the property of the exhibitor for an additional fee of $10.
Each panel measures 25 1/4”x 19 1/4”x 2” (height/width/depth)

Whether you want to rent 3 pieces or 40 pieces, we will work to meet your needs.
Here are some general ideas. 

10 reproductions - $1,500 + shipping and insurance
Linear feet needed - 40

15 reproductions - $2,000 + shipping and insurance
Linear feet needed - 60

20 reproductions - $2,500 + shipping and insurance
Linear feet needed - 80

30 reproductions - $3,500 + shipping and insurance
Linear feet needed - 120

Duration of exhibition – 3 months – which is inclusive of shipping time

Add Ons-
Public Talk - $2,500 plus travel expenses, room and board
Workshop - $ 3,500
	Purchase - Reproductions in the exhibition may be purchased for $175 unframed.

Suggested Installation information

1. When unpacking a box, always note how the contents have been wrapped and placed. Keep all the original packing material to use when repacking.  Fill out condition report as you are unpacking.
2. When staging two-dimensional pieces, place them upright against the wall, face-to-face and back-to-back, with separators between faces. Stack similarly sized works together. Never lay panels or framed works flat on the floor, and use rubber or non-skid pads to prevent slipping and to protect the bottom of the objects.
3.  All works are wired ready to be wall mounted.  We will provide easels if you do not have a designated gallery.
4. When hanging two-dimensional works, position the center of the object at standard eye level. This is generally considered to be 60"-64" from the floor.
5.  We suggest around 24” between each artwork.  This can be adjusted as your individual space requires.  The artwork can also be broken up into smaller groups or units if space demands.





Don’t think you have to have a gallery space within a state of the art institution to book our exhibition.   Our works have been displayed in church parlors, doctor’s waiting rooms, office break rooms, bank and theatre lobbies.  Our staff will assist you in finding just the right space within your facility.
<br><br>
Exhibitor Responsibilities<br>
The exhibitor is responsible for booking reservations, publicity, unpacking and repacking of show, handling and hanging of shows, picking up and returning the exhibits (if within driving distance – otherwise shipping arrangements will be made) and assumes liability for rented exhibitions. 
<br><br>
Payment<br>
If the exhibition is available, exhibitors will receive a confirmation letter and rental-fee invoice.  Payment should be sent no fewer than 30 days before the scheduled pick-up/ delivery time of the exhibition.  Invoices must be paid in full before any exhibition is released.
Information<br>
TEP Coordinator<br>
803-429-4151<br>
Info@healingicons.org<br>
<br><br>
Exhibitions<br>
This features 2-D and 3-D full-color fine art reproductions of mixed media artwork created by adult cancer patients.  Every exhibition contains two original works of art to enhance the viewer’s experience.<br>

All works are mounted on foam core, sealed with a protective coating and framed without glass in a light weight brush metal molding, wired for hanging
Each exhibition includes an introduction panel and two process panels showing students working. <br>
An informational DVD <br>
Each panel measures  25 1/4”x 19 1/4”x 2” (height/width/depth)<br>

Whether you want to rent 3 pieces or 40 pieces, we will work to meet your needs.<br>
Here are some general ideas.<br>
<br>
<br>
10 reproductions - $1,000 + shipping and insurance<br>
Linear feet needed - 40<br>

15 reproductions - $1,500 + shipping and insurance<br>
Linear feet needed - 60<br>

20 reproductions - $2,000 + shipping and insurance<br>
Linear feet needed - 80<br>

30 reproductions - $3,000 = shipping and insurance<br>
Linear feet needed - 120<br>

Duration of exhibition – 3 months – which is inclusive of shipping time<br>
<br>
Add Ons-<br>
Public Talk - $2,500 plus travel expenses, room and board<br>
Workshop - $ 3,500<br>
	Purchase - Reproductions in the exhibition may be purchased for $175 unframed.<br>
<br><br>
Suggested Installation information
<br>
1. When unpacking a box, always note how the contents have been wrapped and placed. Keep all the original packing material to use when repacking.  Fill out condition report as you are unpacking.<br>
2. When staging two-dimensional pieces, place them upright against the wall, face-to-face and back-to-back, with separators between faces. Stack similarly sized works together. Never lay panels or framed works flat on the floor, and use rubber or non-skid pads to prevent slipping and to protect the bottom of the objects.<br>
3.  All works are wired ready to be wall mounted.  We will provide easels if you do not have a designated gallery.<br>
4. When hanging two-dimensional works, position the center of the object at standard eye level. This is generally considered to be 60"-64" from the floor.
5.  We suggest around 24” between each artwork.  The artwork can be broken up into smaller groups or units if space demands.<br>
</div>

app/views/pages/press.html.erb
press

app/views/pages/speaker.html.erb
speaker

app/views/pages/teacher.html.erb
Become a teacher